import React from 'react';
import StaticPage from '../containers/StaticPage'
import "../../src/assets/css/pages/StaticPages/PrivacyPolicy.scss";

const PrivacyPolicy = () => {
    return <div>
        <StaticPage>
            <div className="LegalDocumentPage">
                <div className="document-content">
                    <div>
                <meta httpEquiv="Content-Type" content="text/html; charset=utf-8" />
                <title>privacy-notice-en</title>
                <style type="text/css" dangerouslySetInnerHTML={{ __html: "\n        .h1,\n        h1 {\n            font-family: Arial, sans-serif;\n            color: black;\n            font-style: normal;\n            font-weight: bold;\n            text-decoration: none;\n            font-size: 18px;\n            padding-top: 2pt;\n            text-indent: 0pt;\n            text-align: center;\n        }\n\n        .p,\n        p {\n            font-family: Arial, sans-serif;\n            color: black;\n            font-style: normal;\n            font-weight: normal;\n            text-decoration: none;\n            text-align: justify;\n            font-size: 11pt;\n            margin: 12px 0 12px 0;\n        }\n\n        .s2 {\n            color: #0062D3;\n            font-style: normal;\n            font-weight: normal;\n            text-decoration: none;\n            font-size: 11pt;\n        }\n\n        .s3 {\n            color: #252525;\n            font-style: normal;\n            font-weight: bold;\n            font-size: 11pt;\n        }\n\n        .s4 {\n            color: black;\n            font-style: normal;\n            font-weight: bold;\n            font-size: 11pt;\n        }\n\n        .s5 {\n            color: black;\n            font-style: normal;\n            font-weight: normal;\n            font-size: 11pt;\n        }\n\n        .a,\n        a {\n            color: black;\n            font-style: normal;\n            font-weight: normal;\n            text-decoration: none;\n            font-size: 11pt;\n        }\n\n        li {\n            display: block;\n            font-family: Arial, sans-serif;\n            padding-top: 5px;\n        }\n\n        li>p {\n            margin: 0;\n        }\n\n        #l1,\n        #l2,\n        #l3,\n        #l4,\n        #l5,\n        #l6,\n        #l7,\n        #l8,\n        #l9,\n        #l10,\n        #l11 {\n            padding-left: 0pt;\n        }\n\n        #l1>*:first-child:before,\n        #l2>*:first-child:before,\n        #l3>*:first-child:before,\n        #l4>*:first-child:before,\n        #l5>*:first-child:before,\n        #l6>*:first-child:before,\n        #l7>*:first-child:before,\n        #l8>*:first-child:before,\n        #l9>*:first-child:before,\n        #l10>*:first-child:before,\n        #l11>*:first-child:before {\n            content: \"● \";\n            color: black;\n            font-style: normal;\n            font-weight: bold;\n            font-size: 11pt;\n        }\n\n        .inner-link {\n            color: #0062D3;\n            font-weight: 700;\n            text-decoration: underline;\n        }\n    " }} />
                        <p><strong>Chính sách bảo mật</strong></p>
                        <p>&nbsp;</p>
                        <p><strong>Chính sách quyền riêng tư của Mixtiles</strong></p>
                        <p><span style={{fontWeight: 400}}>Chính sách Bảo mật này mô tả cách chúng tôi - Mixtiles Ltd., Mixtiles BV, Mixtiles USA, Inc. và các công ty liên kết của chúng tôi (“Mixtiles”, “chúng tôi”, “của chúng tôi” hoặc “chúng tôi”) - thu thập, lưu trữ, sử dụng và tiết lộ dữ liệu cá nhân liên quan đến các cá nhân (“(Các) người dùng” hoặc “bạn”), những người:</span></p>
                        <p>&nbsp;</p>
                        <p><span style={{fontWeight: 400}}>truy cập, sử dụng hoặc tương tác với trang web của chúng tôi, có sẵn tại www.Mixtilesvietnam.com, hoặc bất kỳ trang web, trang web, e-mail, tin nhắn văn bản hoặc quảng cáo trực tuyến nào khác dưới sự kiểm soát của chúng tôi (gọi chung là “Trang web”);</span></p>
                        <p><span style={{fontWeight: 400}}>tham gia vào Chương trình giới thiệu của chúng tôi, như được mô tả trong Điều khoản giới thiệu ("Chương trình giới thiệu"); và / hoặc</span></p>
                        <p><span style={{fontWeight: 400}}>sử dụng các ứng dụng web và ứng dụng di động của chúng tôi (cùng với Chương trình Trang web và Giới thiệu - “Dịch vụ”), cho phép họ in hình ảnh và tranh ảnh (“Hình ảnh”) lên gạch ốp tường và giao cho họ (tất cả đều tuân theo Điều khoản của chúng tôi dịch vụ).</span></p>
                        <p><span style={{fontWeight: 400}}>Cụ thể, Chính sách Bảo mật này mô tả các thực tiễn của chúng tôi liên quan đến -</span></p>
                        <p>&nbsp;</p>
                        <p><span style={{fontWeight: 400}}>Thu thập dữ liệu</span></p>
                        <p><span style={{fontWeight: 400}}>Sử dụng dữ liệu</span></p>
                        <p><span style={{fontWeight: 400}}>Vị trí dữ liệu</span></p>
                        <p><span style={{fontWeight: 400}}>Lưu trữ dữ liệu</span></p>
                        <p><span style={{fontWeight: 400}}>Chia sẻ dữ liệu</span></p>
                        <p><span style={{fontWeight: 400}}>Cookie và Công nghệ Theo dõi</span></p>
                        <p><span style={{fontWeight: 400}}>Thông tin liên lạc</span></p>
                        <p><span style={{fontWeight: 400}}>Bảo mật dữ liệu</span></p>
                        <p><span style={{fontWeight: 400}}>Quyền đối tượng dữ liệu</span></p>
                        <p><span style={{fontWeight: 400}}>Bộ điều khiển / Bộ xử lý dữ liệu</span></p>
                        <p><span style={{fontWeight: 400}}>Thông tin bổ sung và chi tiết liên hệ</span></p>
                        <p>&nbsp;</p>
                        <p><span style={{fontWeight: 400}}>Quyền riêng tư rất quan trọng đối với chúng tôi và chúng tôi cam kết mạnh mẽ về tính minh bạch và công bằng trong các hoạt động xử lý dữ liệu của mình. Vui lòng đọc kỹ Chính sách Bảo mật này và đảm bảo rằng bạn hoàn toàn hiểu và đồng ý với các thông lệ của chúng tôi. Hãy nhớ rằng: về mặt pháp lý bạn không bắt buộc phải cung cấp cho chúng tôi bất kỳ dữ liệu cá nhân nào và có thể làm như vậy (hoặc tránh làm như vậy) theo ý muốn của riêng bạn.</span></p>
                        <p>&nbsp;</p>
                        <p><span style={{fontWeight: 400}}>Nếu bạn không muốn cung cấp cho chúng tôi dữ liệu cá nhân của bạn hoặc để chúng tôi xử lý dữ liệu đó, vui lòng không sử dụng Dịch vụ của chúng tôi. Bạn cũng có thể yêu cầu xóa một số dữ liệu nhất định hoặc chọn không tham gia một số hoạt động xử lý nhất định (xem Phần 9), nhưng xin lưu ý rằng việc hạn chế xử lý của chúng tôi cũng có thể dẫn đến việc chúng tôi không thể cung cấp cho bạn đầy đủ các Dịch vụ của chúng tôi hoặc với trải nghiệm người dùng tốt nhất khi sử dụng Dịch vụ của chúng tôi.</span></p>
                        <p>&nbsp;</p>
                        <p><strong>Thu thập dữ liệu</strong></p>
                        <p><span style={{fontWeight: 400}}>Chúng tôi thu thập các danh mục dữ liệu sau (trong phạm vi liên quan đến một cá nhân được xác định hoặc có thể nhận dạng, sẽ được coi là “Dữ liệu Cá nhân”):</span></p>
                        <p>&nbsp;</p>
                        <p><span style={{fontWeight: 400}}>Dữ liệu được thu thập hoặc tạo tự động: Khi bạn tương tác với hoặc sử dụng Dịch vụ của chúng tôi, chúng tôi có thể thu thập một số dữ liệu kỹ thuật nhất định về bạn như hệ điều hành, địa chỉ IP, số nhận dạng thiết bị của bạn và tùy thuộc vào sự đồng ý của bạn nếu có thể được yêu cầu theo luật hiện hành, (địa lý ) vị trí, cũng như lịch sử duyệt web của bạn và mọi dữ liệu liên quan đến lịch sử mua hàng của bạn trên Dịch vụ của chúng tôi. Chúng tôi thu thập hoặc tạo dữ liệu đó một cách độc lập hoặc với sự trợ giúp của các Nhà cung cấp dịch vụ của chúng tôi (như được nêu chi tiết trong Phần 5 dưới đây), bao gồm thông qua việc sử dụng "cookie" và các công nghệ theo dõi khác (như được nêu chi tiết trong Phần 6 bên dưới).</span></p>
                        <p>&nbsp;</p>
                        <p><span style={{fontWeight: 400}}>Dữ liệu nhận được từ bạn: Bạn có thể cung cấp cho chúng tôi Dữ liệu Cá nhân như tên, e-mail, số điện thoại, địa chỉ giao hàng và phương thức thanh toán (thẻ tín dụng hoặc PayPal) và bất kỳ dữ liệu nào khác mà bạn chọn cung cấp khi liên hệ với chúng tôi hoặc theo cách khác gửi bất kỳ biểu mẫu nào trên Dịch vụ của chúng tôi.</span></p>
                        <p>&nbsp;</p>
                        <p><span style={{fontWeight: 400}}>Hình ảnh bạn tải lên: Dịch vụ của chúng tôi cho phép bạn chọn và tải lên Hình ảnh, độc lập với thiết bị của bạn hoặc thông qua liên kết tài khoản của bạn trên các trang web hoặc phương tiện truyền thông xã hội khác (chẳng hạn như tài khoản Facebook hoặc Google của bạn) và sau khi được liên kết, chúng tôi sẽ có quyền truy cập hạn chế vào dữ liệu và Hình ảnh nhất định trên (các) tài khoản được liên kết đó.</span></p>
                        <p>&nbsp;</p>
                        <p><span style={{fontWeight: 400}}>Dữ liệu nhận được từ các dịch vụ của bên thứ ba: Dịch vụ của chúng tôi có thể được sử dụng cùng với các dịch vụ, trang web và ứng dụng di động của bên thứ ba. Nếu bạn sử dụng Dịch vụ của chúng tôi với hoặc thông qua các bên thứ ba đó, chúng tôi có thể nhận Dữ liệu Cá nhân về bạn từ các bên thứ ba đó. Xin lưu ý rằng khi bạn sử dụng các dịch vụ, trang web và ứng dụng di động của bên thứ ba đó, các điều khoản và chính sách bảo mật của chính họ sẽ chi phối việc bạn sử dụng các dịch vụ đó.</span></p>
                        <p>&nbsp;</p>
                        <p><span style={{fontWeight: 400}}>Dữ liệu thu được thông qua Công cụ Analytics: Chúng tôi sử dụng các công cụ phân tích (ví dụ: Google Analytics) để thu thập dữ liệu về việc sử dụng Trang web và Dịch vụ của chúng tôi. Các công cụ phân tích thu thập dữ liệu như tần suất Người dùng truy cập hoặc sử dụng Trang web hoặc Dịch vụ, họ truy cập trang nào và khi nào cũng như trang web, quảng cáo hoặc thông báo e-mail nào đã đưa họ đến đó. Bạn có thể tìm thêm thông tin về cách Google thu thập thông tin và cách bạn có thể kiểm soát việc sử dụng đó tại https://policies.google.com/technologies/partner-sites.</span></p>
                        <p>&nbsp;</p>
                        <p><strong>Sử dụng dữ liệu</strong></p>
                        <p><span style={{fontWeight: 400}}>Chúng tôi sử dụng Dữ liệu Cá nhân của bạn khi cần thiết để thực hiện Dịch vụ của chúng tôi; để tuân thủ luật hiện hành; và dựa trên lợi ích hợp pháp của chúng tôi trong việc duy trì và cải thiện Dịch vụ và các dịch vụ của chúng tôi, hiểu cách Dịch vụ của chúng tôi được sử dụng, tối ưu hóa hoạt động tiếp thị, dịch vụ khách hàng và hỗ trợ của chúng tôi, đồng thời bảo vệ và đảm bảo an toàn cho Người dùng của chúng tôi, bản thân chúng tôi và các thành viên của công chúng.</span></p>
                        <p>&nbsp;</p>
                        <p><span style={{fontWeight: 400}}>Nếu bạn cư trú hoặc đang sử dụng Dịch vụ (i) trong lãnh thổ được điều chỉnh bởi luật bảo mật xác định rằng "sự đồng ý" là cơ sở pháp lý duy nhất để xử lý dữ liệu cá nhân (nói chung hoặc cụ thể đối với các loại Dữ liệu cá nhân của bạn chọn chia sẻ qua Dịch vụ) hoặc (ii) trong EEA và cung cấp cho chúng tôi Dữ liệu cá nhân, việc xử lý dữ liệu đó yêu cầu “sự đồng ý” theo luật hiện hành (ví dụ: 'danh mục đặc biệt' của dữ liệu cá nhân theo GDPR), sự chấp nhận của bạn đối với Điều khoản Dịch vụ và Chính sách Bảo mật này sẽ được coi là sự đồng ý của bạn đối với việc xử lý Dữ liệu Cá nhân của bạn cho tất cả các mục đích được nêu chi tiết trong Chính sách Bảo mật này. Nếu bạn muốn rút lại sự đồng ý đó, vui lòng liên hệ với chúng tôi tại hi@Mixtilesvietnam.com.</span></p>
                        <p>&nbsp;</p>
                        <p><span style={{fontWeight: 400}}>Cụ thể, chúng tôi sử dụng Dữ liệu Cá nhân cho các mục đích sau:</span></p>
                        <p>&nbsp;</p>
                        <p><span style={{fontWeight: 400}}>Để tạo điều kiện, vận hành và cung cấp Dịch vụ;</span></p>
                        <p><span style={{fontWeight: 400}}>Để xác thực danh tính của Người dùng của chúng tôi và cho phép họ truy cập và sử dụng Dịch vụ của chúng tôi;</span></p>
                        <p><span style={{fontWeight: 400}}>Để cung cấp cho Người dùng của chúng tôi sự trợ giúp và hỗ trợ;</span></p>
                        <p><span style={{fontWeight: 400}}>Để phát triển, tùy chỉnh và cải thiện Dịch vụ cũng như trải nghiệm của Người dùng của chúng tôi, dựa trên sở thích, trải nghiệm, khó khăn và phản hồi chung hoặc cá nhân;</span></p>
                        <p><span style={{fontWeight: 400}}>Để cắt chính xác Hình ảnh bạn tải lên thông qua việc sử dụng phần mềm nhận dạng khuôn mặt (chỉ cho mục đích như vậy);</span></p>
                        <p><span style={{fontWeight: 400}}>Để liên hệ với Người dùng của chúng tôi bằng các tin nhắn liên quan đến dịch vụ chung hoặc được cá nhân hóa (chẳng hạn như lấy lại mật khẩu hoặc thanh toán); hoặc với các thông điệp quảng cáo (chẳng hạn như bản tin, ưu đãi đặc biệt, tính năng mới, v.v.); và để tạo điều kiện, tài trợ và cung cấp các sự kiện và chương trình khuyến mãi nhất định;</span></p>
                        <p><span style={{fontWeight: 400}}>Để hỗ trợ và tăng cường các biện pháp bảo mật dữ liệu của chúng tôi, bao gồm cho các mục đích ngăn ngừa và giảm thiểu rủi ro gian lận, sai sót hoặc bất kỳ hoạt động bất hợp pháp hoặc bị cấm nào;</span></p>
                        <p><span style={{fontWeight: 400}}>Để tạo dữ liệu thống kê tổng hợp, dữ liệu phi cá nhân được phỏng đoán hoặc dữ liệu ẩn danh hoặc bí danh (được hiển thị phi cá nhân), mà chúng tôi hoặc các đối tác kinh doanh của chúng tôi có thể sử dụng để cung cấp và cải thiện các dịch vụ tương ứng của chúng tôi; và</span></p>
                        <p><span style={{fontWeight: 400}}>Để tuân thủ bất kỳ luật và quy định hiện hành nào.</span></p>
                        <p><span style={{fontWeight: 400}}>Chúng tôi không bán Dữ liệu Cá nhân của bạn (hoặc "Thông tin Cá nhân" theo Đạo luật Quyền riêng tư của Người tiêu dùng California - CCPA) cho mục đích và mục đích của CCPA.</span></p>
                        <p><span style={{fontWeight: 400}}>Vị trí dữ liệu</span></p>
                        <p><span style={{fontWeight: 400}}>Chúng tôi và các Nhà cung cấp Dịch vụ được ủy quyền của chúng tôi (được định nghĩa bên dưới) duy trì, lưu trữ và xử lý Dữ liệu Cá nhân ở Hoa Kỳ, Israel, Liên minh Châu Âu và các địa điểm khác khi cần thiết một cách hợp lý để thực hiện đúng và phân phối Dịch vụ của chúng tôi, hoặc theo yêu cầu của pháp luật .</span></p>
                        <p>&nbsp;</p>
                        <p><span style={{fontWeight: 400}}>Mixtiles Ltd. có trụ sở chính tại Israel, một cơ quan tài phán được Ủy ban Châu Âu coi là cung cấp mức độ bảo vệ thích hợp cho Dữ liệu Cá nhân của cư dân Quốc gia Thành viên EU. Mặc dù luật về quyền riêng tư có thể khác nhau giữa các khu vực pháp lý, Mixtiles và các chi nhánh và Nhà cung cấp dịch vụ đều cam kết bảo vệ Dữ liệu cá nhân theo Chính sách quyền riêng tư này, các tiêu chuẩn ngành thông thường và các cơ chế hợp pháp thích hợp như vậy và các điều khoản hợp đồng yêu cầu bảo vệ dữ liệu đầy đủ, bất kể mức thấp hơn nào các yêu cầu pháp lý có thể áp dụng tại khu vực tài phán mà dữ liệu đó bắt nguồn từ đó.</span></p>
                        <p>&nbsp;</p>
                        <p><strong>Lưu trữ dữ liệu</strong></p>
                        <p><span style={{fontWeight: 400}}>Chúng tôi chỉ lưu giữ dữ liệu khi cần thiết cho các mục đích được mô tả trong Chính sách Bảo mật này.</span></p>
                        <p>&nbsp;</p>
                        <p><span style={{fontWeight: 400}}>Để xác định khoảng thời gian lưu giữ thích hợp, chúng tôi xem xét số lượng, bản chất và độ nhạy cảm của Dữ liệu Cá nhân, nguy cơ có thể bị tổn hại do sử dụng trái phép hoặc tiết lộ Dữ liệu Cá nhân của bạn, các mục đích mà chúng tôi xử lý Dữ liệu Cá nhân của bạn và liệu những mục đích đó có thể đạt được thông qua các phương tiện khác, cũng như các yêu cầu pháp lý hiện hành.</span></p>
                        <p>&nbsp;</p>
                        <p><span style={{fontWeight: 400}}>Chúng tôi cũng sẽ lưu giữ và sử dụng Dữ liệu Cá nhân đó miễn là được yêu cầu để tuân thủ các nghĩa vụ pháp lý và hợp đồng của chúng tôi hoặc để bảo vệ bản thân khỏi bất kỳ tranh chấp tiềm ẩn nào (tức là theo yêu cầu của luật áp dụng đối với hồ sơ và sổ sách kế toán, và để để có bằng chứng và bằng chứng liên quan đến mối quan hệ của chúng tôi hoặc việc bạn sử dụng Dịch vụ của chúng tôi, nếu có bất kỳ vấn đề pháp lý nào phát sinh trong tương lai), theo chính sách lưu giữ dữ liệu của chúng tôi.</span></p>
                        <p>&nbsp;</p>
                        <p><span style={{fontWeight: 400}}>Hình ảnh cụ thể sẽ được giữ lại cho đến khi tài khoản của bạn bị chấm dứt, bởi chúng tôi hoặc bởi bạn. Bất kỳ Hình ảnh nào đã được tải lên Dịch vụ nhưng cuối cùng không được chọn để in trên các ô sẽ tự động bị xóa, sau ba mươi (30) ngày kể từ ngày bạn tải lên (các) Hình ảnh.</span></p>
                        <p>&nbsp;</p>
                        <p><span style={{fontWeight: 400}}>Bạn có thể yêu cầu chúng tôi xóa bất kỳ Dữ liệu Cá nhân nào, bao gồm cả Hình ảnh, bằng cách gửi cho chúng tôi email như đã nêu trong Phần 9 bên dưới. Chúng tôi có thể xóa bất kỳ dữ liệu hoặc Hình ảnh nào khỏi hệ thống của mình mà không cần thông báo cho bạn, kể cả khi chúng tôi cho rằng nó không còn cần thiết cho các mục đích được nêu trong Chính sách Bảo mật này. Chúng tôi cũng có thể giữ lại dữ liệu của bạn ở dạng ẩn danh.</span></p>
                        <p>&nbsp;</p>
                        <p><span style={{fontWeight: 400}}>Xin lưu ý rằng trừ khi luật hiện hành yêu cầu, chúng tôi sẽ không có nghĩa vụ phải giữ lại dữ liệu của bạn trong bất kỳ khoảng thời gian cụ thể nào và có thể tự do xóa dữ liệu đó một cách an toàn vì bất kỳ lý do gì và bất kỳ lúc nào, có hoặc không thông báo cho bạn.</span></p>
                        <p>&nbsp;</p>
                        <p><span style={{fontWeight: 400}}>Nếu bạn có bất kỳ câu hỏi nào về chính sách lưu giữ dữ liệu của chúng tôi, vui lòng liên hệ với chúng tôi theo địa chỉ: hi@Mixtilesvietnam.com.</span></p>
                        <p>&nbsp;</p>
                        <p><strong>Chia sẻ dữ liệu</strong></p>
                        <p><span style={{fontWeight: 400}}>Tuân thủ pháp lý: chúng tôi có thể tiết lộ hoặc cho phép các quan chức chính phủ và cơ quan thực thi pháp luật truy cập vào Dữ liệu cá nhân nhất định, theo trát đòi hầu tòa, lệnh khám xét hoặc lệnh tòa (hoặc yêu cầu tương tự) hoặc tuân theo các luật và quy định hiện hành. Việc tiết lộ hoặc truy cập như vậy có thể xảy ra nếu chúng tôi tin rằng chúng tôi buộc phải làm như vậy về mặt pháp lý và chỉ trong phạm vi mà chúng tôi tin rằng là thực sự cần thiết để tuân thủ hoặc rằng việc tiết lộ đó là phù hợp liên quan đến nỗ lực điều tra, ngăn chặn hoặc thực hiện hành động liên quan đến hoạt động bất hợp pháp thực tế hoặc bị nghi ngờ, gian lận hoặc hành vi sai trái khác.</span></p>
                        <p>&nbsp;</p>
                        <p><span style={{fontWeight: 400}}>Nhà cung cấp dịch vụ: chúng tôi có thể thu hút các đối tác kinh doanh được chọn, các công ty và cá nhân bên thứ ba, chi nhánh, nhà thầu phụ và nhà xử lý phụ (gọi chung là “Nhà cung cấp dịch vụ”) để thực hiện các dịch vụ bổ sung cho chính chúng tôi (ví dụ: sản xuất, in ấn và dịch vụ vận chuyển, xử lý thanh toán Dịch vụ CNTT và quản trị hệ thống, sao lưu dữ liệu, dịch vụ bảo mật và lưu trữ, phân tích dữ liệu, tiếp thị, v.v.). Các Nhà cung cấp Dịch vụ này có thể có quyền truy cập vào một số hoặc tất cả Dữ liệu Cá nhân của bạn do chúng tôi xử lý, tùy thuộc vào từng vai trò và mục đích cụ thể của họ trong việc tạo điều kiện và nâng cao Dịch vụ của chúng tôi, và chỉ có thể sử dụng nó cho các mục đích như vậy.</span></p>
                        <p>&nbsp;</p>
                        <p><span style={{fontWeight: 400}}>Chia sẻ Phản hồi hoặc Đề xuất của bạn: Nếu bạn gửi đánh giá hoặc phản hồi công khai, hãy lưu ý rằng chúng tôi có thể (theo quyết định của chúng tôi) lưu trữ và trình bày đánh giá của bạn cho những người dùng khác trên Trang web và Dịch vụ của chúng tôi. Nếu bạn muốn xóa bài đánh giá công khai của mình, vui lòng liên hệ với chúng tôi tại hi@Mixtilesvietnam.com. Nếu bạn chọn gửi cho người khác một e-mail hoặc tin nhắn mời họ sử dụng Dịch vụ (bao gồm cả thông qua Chương trình giới thiệu), chúng tôi sẽ sử dụng thông tin liên hệ mà bạn cung cấp cho chúng tôi để tự động gửi e-mail hoặc tin nhắn mời đó thay mặt cho bạn. Tên và địa chỉ e-mail của bạn có thể được bao gồm trong e-mail hoặc tin nhắn mời.</span></p>
                        <p>&nbsp;</p>
                        <p><span style={{fontWeight: 400}}>Bảo vệ Quyền và An toàn: chúng tôi có thể chia sẻ Dữ liệu Cá nhân của bạn với những người khác nếu chúng tôi tin tưởng thành thực rằng điều này sẽ giúp bảo vệ quyền, tài sản hoặc sự an toàn cá nhân của Mixtiles, bất kỳ Người dùng nào của chúng tôi hoặc bất kỳ thành viên nào của công chúng.</span></p>
                        <p>&nbsp;</p>
                        <p><strong>Cookie và Công nghệ Theo dõi</strong></p>
                        <p><span style={{fontWeight: 400}}>Dịch vụ của chúng tôi và một số Nhà cung cấp dịch vụ của chúng tôi sử dụng "cookie", số nhận dạng ẩn danh, thẻ vùng chứa và các công nghệ theo dõi khác giúp chúng tôi cung cấp, bảo mật, phân tích và cải thiện Dịch vụ của mình, cá nhân hóa trải nghiệm của bạn cũng như giám sát và phân tích hiệu suất của các hoạt động và chiến dịch của chúng tôi.</span></p>
                        <p>&nbsp;</p>
                        <p><span style={{fontWeight: 400}}>Các cookie như vậy và các tệp hoặc thẻ tương tự cũng có thể được đặt tạm thời trên thiết bị của bạn. Một số cookie nhất định và các công nghệ khác phục vụ để gọi lại Dữ liệu Cá nhân, chẳng hạn như địa chỉ IP, được Người dùng chỉ ra trước đó.</span></p>
                        <p>&nbsp;</p>
                        <p><span style={{fontWeight: 400}}>Xin lưu ý rằng chúng tôi không thay đổi các hoạt động của mình để phản hồi lại tín hiệu “Không theo dõi” trong tiêu đề HTTP từ trình duyệt hoặc ứng dụng dành cho thiết bị di động, tuy nhiên, hầu hết các trình duyệt đều cho phép bạn kiểm soát cookie, bao gồm cả việc có chấp nhận chúng hay không và cách loại bỏ chúng. Bạn có thể đặt hầu hết các trình duyệt để thông báo cho bạn nếu bạn nhận được cookie hoặc bạn có thể chọn chặn cookie bằng trình duyệt của mình.</span></p>
                        <p>&nbsp;</p>
                        <p><span style={{fontWeight: 400}}>Để tìm hiểu thêm về các thực tiễn của chúng tôi liên quan đến cookie và theo dõi trực tuyến, vui lòng truy cập Chính sách cookie của chúng tôi.</span></p>
                        <p>&nbsp;</p>
                        <p><strong>Thông tin liên lạc</strong></p>
                        <p><span style={{fontWeight: 400}}>Truyền thông Dịch vụ: chúng tôi có thể liên hệ với bạn với thông tin quan trọng liên quan đến Dịch vụ của chúng tôi. Ví dụ: chúng tôi có thể thông báo cho bạn (thông qua bất kỳ phương tiện nào có sẵn cho chúng tôi) về tóm tắt đơn hàng và cập nhật giao hàng, các thay đổi hoặc cập nhật đối với Dịch vụ của chúng tôi, các vấn đề về thanh toán, v.v. Bạn sẽ không thể chọn không nhận các thông báo dịch vụ đó .</span></p>
                        <p>&nbsp;</p>
                        <p><span style={{fontWeight: 400}}>Thông báo và Truyền thông Khuyến mại: chúng tôi có thể gửi cho bạn tin nhắn và thông báo về các tính năng mới, dịch vụ, sự kiện và cơ hội đặc biệt cũng như bất kỳ thông tin nào khác mà chúng tôi cho rằng Người dùng của chúng tôi sẽ thấy có giá trị. Chúng tôi có thể cung cấp các thông báo như vậy thông qua bất kỳ phương tiện liên hệ nào có sẵn cho chúng tôi (ví dụ: SMS, thông báo trên điện thoại di động hoặc e-mail), thông qua Dịch vụ hoặc thông qua các chiến dịch tiếp thị của chúng tôi trên bất kỳ trang web hoặc nền tảng nào khác.</span></p>
                        <p>&nbsp;</p>
                        <p><span style={{fontWeight: 400}}>Nếu bạn không muốn nhận các thông báo quảng cáo như vậy qua SMS, thông báo hoặc e-mail, bạn có thể thông báo cho Mixtiles bất kỳ lúc nào bằng cách gửi email cho chúng tôi tại địa chỉ athi@Mixtilesvietnam.com hoặc bằng cách thực hiện theo "hủy đăng ký", "dừng" hoặc "thay đổi e -tùy chọn email "hướng dẫn có trong thông báo khuyến mại mà bạn nhận được.</span></p>
                        <p>&nbsp;</p>
                        <p><strong>Bảo mật dữ liệu</strong></p>
                        <p><span style={{fontWeight: 400}}>Để bảo vệ Dữ liệu Cá nhân của bạn được lưu giữ với chúng tôi và Nhà cung cấp dịch vụ của chúng tôi, chúng tôi đang sử dụng các biện pháp bảo mật vật lý, thủ tục và điện tử tiêu chuẩn ngành (chẳng hạn như kiểm soát truy cập, máy chủ bảo mật, tường lửa, chính sách nội bộ, mã hóa, sao lưu cơ sở dữ liệu, v.v.). Tuy nhiên, xin lưu ý rằng bất kể biện pháp bảo mật nào được sử dụng, chúng tôi không thể và không đảm bảo sự bảo vệ và bảo mật tuyệt đối cho bất kỳ Dữ liệu Cá nhân nào được lưu trữ với chúng tôi hoặc với bất kỳ bên thứ ba nào.</span></p>
                        <p>&nbsp;</p>
                        <p><strong>Quyền đối tượng dữ liệu</strong></p>
                        <p><span style={{fontWeight: 400}}>Các cá nhân có quyền liên quan đến Dữ liệu Cá nhân của họ. Nếu bạn muốn thực hiện quyền riêng tư của mình theo luật áp dụng cho bạn (ví dụ: Quy định chung về bảo vệ dữ liệu của Liên minh Châu Âu (GDPR) hoặc Đạo luật về quyền riêng tư của người tiêu dùng California (CCPA)), chẳng hạn như quyền yêu cầu truy cập và cải chính hoặc xóa Dữ liệu cá nhân của bạn được lưu giữ với Mixtiles, hoặc để hạn chế hoặc phản đối việc xử lý Dữ liệu cá nhân đó, hoặc chuyển Dữ liệu cá nhân đó hoặc quyền được hưởng các dịch vụ và giá cả như nhau (mỗi thứ trong phạm vi có sẵn cho bạn theo luật áp dụng cho bạn) - vui lòng liên hệ với chúng tôi qua e-mail tại: hi@Mixtilesvietnam.com.</span></p>
                        <p>&nbsp;</p>
                        <p><span style={{fontWeight: 400}}>Cũng xin lưu ý rằng một số Dữ liệu Cá nhân của bạn có thể được xử lý bởi các bên khác đóng vai trò là "người kiểm soát dữ liệu", như chi tiết trong Phần 10 bên dưới, chẳng hạn như Facebook và Google. Đối với bất kỳ yêu cầu nào để thực hiện các quyền đó đối với các hoạt động xử lý của các bên đó, vui lòng liên hệ trực tiếp với bên có liên quan.</span></p>
                        <p>&nbsp;</p>
                        <p><span style={{fontWeight: 400}}>Khi bạn yêu cầu chúng tôi thực hiện bất kỳ quyền nào của bạn theo Chính sách quyền riêng tư này hoặc luật hiện hành, chúng tôi có thể cần yêu cầu bạn cung cấp cho chúng tôi một số thông tin xác thực nhất định để đảm bảo rằng bạn là chính mình, để tránh tiết lộ Dữ liệu cá nhân liên quan đến cá nhân và yêu cầu bạn cung cấp thêm thông tin để hiểu rõ hơn về bản chất và phạm vi dữ liệu mà bạn muốn truy cập hoặc đã xóa, v.v. Dữ liệu bổ sung đó sau đó sẽ được chúng tôi lưu giữ cho các mục đích pháp lý (ví dụ như bằng chứng về danh tính của người gửi yêu cầu), theo Mục 4 ở trên. Chúng tôi có thể biên tập lại dữ liệu mà chúng tôi sẽ cung cấp cho bạn, bất kỳ dữ liệu cá nhân nào liên quan đến người khác.</span></p>
                        <p>&nbsp;</p>
                        <p><strong>Bộ điều khiển / Bộ xử lý dữ liệu</strong></p>
                        <p><span style={{fontWeight: 400}}>Một số luật và quy định về bảo vệ dữ liệu nhất định, chẳng hạn như GDPR hoặc CCPA, thường phân biệt giữa hai vai trò chính đối với các bên xử lý Dữ liệu cá nhân: “người kiểm soát dữ liệu” (hoặc theo CCPA, “doanh nghiệp”), người xác định mục đích và phương tiện của Chế biến; và “bộ xử lý dữ liệu” (hoặc theo CCPA, “nhà cung cấp dịch vụ”), người xử lý dữ liệu thay mặt cho bộ kiểm soát dữ liệu (hoặc doanh nghiệp). Dưới đây, chúng tôi giải thích cách các vai trò này áp dụng cho Dịch vụ của chúng tôi, trong phạm vi áp dụng các luật và quy định đó.</span></p>
                        <p>&nbsp;</p>
                        <p><span style={{fontWeight: 400}}>Mixtile là “người kiểm soát dữ liệu” đối với dữ liệu của Người dùng và đảm nhận các trách nhiệm của người kiểm soát dữ liệu (chỉ trong phạm vi áp dụng theo luật), như được quy định trong Chính sách quyền riêng tư này. Trong những trường hợp như vậy, Nhà cung cấp dịch vụ của chúng tôi xử lý dữ liệu đó sẽ đảm nhận vai trò "bộ xử lý dữ liệu".</span></p>
                        <p>&nbsp;</p>
                        <p><span style={{fontWeight: 400}}>Mixtile là "người đồng kiểm soát" đối với một số phần nhất định trong dữ liệu của Người dùng, cùng với Nhà cung cấp dịch vụ xử lý Dữ liệu cá nhân cho cả mục đích phân tích và tiếp thị của Mixtiles - và mục đích riêng của Nhà cung cấp dịch vụ. Trong những trường hợp như vậy, các Nhà cung cấp dịch vụ như vậy (ví dụ: Facebook và Google) trong những trường hợp như vậy sẽ được coi là “người đồng kiểm soát” dữ liệu đó, thường liên quan đến Người dùng cũng sử dụng nền tảng riêng của Nhà cung cấp dịch vụ. Nếu bạn muốn giới hạn các hoạt động độc lập như vậy của các Nhà cung cấp dịch vụ này, hãy xem xét việc tắt cookie của bên thứ ba như được nêu chi tiết trong Mục 6 ở trên.</span></p>
                        <p>&nbsp;</p>
                        <p><strong>Thông tin bổ sung và chi tiết liên hệ</strong></p>
                        <p><span style={{fontWeight: 400}}>Cập nhật và sửa đổi: chúng tôi có thể cập nhật và sửa đổi Chính sách Bảo mật này theo thời gian bằng cách đăng một phiên bản sửa đổi trên Dịch vụ của chúng tôi. Phiên bản sửa đổi sẽ có hiệu lực kể từ ngày có hiệu lực được công bố. Chúng tôi sẽ thông báo trước 10 ngày nếu có bất kỳ thay đổi quan trọng nào có liên quan, thông qua bất kỳ phương tiện liên lạc nào có sẵn cho chúng tôi hoặc trên Dịch vụ. Sau khoảng thời gian thông báo này, tất cả các sửa đổi sẽ được coi là bạn đã chấp nhận.</span></p>
                        <p>&nbsp;</p>
                        <p><span style={{fontWeight: 400}}>Liên kết bên ngoài: trong khi Dịch vụ của chúng tôi có thể chứa các liên kết đến các trang web hoặc dịch vụ khác, chúng tôi không chịu trách nhiệm về các thực tiễn bảo mật của họ và khuyến khích bạn chú ý và đọc chính sách bảo mật của từng trang web và dịch vụ mà bạn truy cập. Chính sách Bảo mật này chỉ áp dụng cho Dịch vụ của chúng tôi.</span></p>
                        <p>&nbsp;</p>
                        <p><span style={{fontWeight: 400}}>Dịch vụ của chúng tôi không được thiết kế để thu hút trẻ em dưới 16 tuổi: chúng tôi không cố ý thu thập Dữ liệu Cá nhân từ trẻ em và không muốn làm như vậy. Nếu chúng tôi biết rằng một đứa trẻ đang sử dụng Dịch vụ, chúng tôi sẽ cố gắng ngăn cấm và chặn việc sử dụng đó cũng như xóa ngay mọi Dữ liệu Cá nhân được chúng tôi lưu trữ mà chúng tôi cho là có liên quan đến đứa trẻ đó. Nếu bạn tin rằng chúng tôi có thể có bất kỳ dữ liệu nào như vậy, vui lòng liên hệ với chúng tôi theo địa chỉ dpo@Mixtilesvietnam.com.</span></p>
                        <p>&nbsp;</p>
                        <p><span style={{fontWeight: 400}}>Cán bộ bảo vệ dữ liệu: Mixtiles đã bổ nhiệm ông Aner Rabinovitz của PrivacyTeam làm Cán bộ bảo vệ dữ liệu (DPO) của chúng tôi, để giám sát và tư vấn về việc tuân thủ quyền riêng tư liên tục của Mixtiles và đóng vai trò là đầu mối liên hệ về các vấn đề quyền riêng tư cho các chủ thể dữ liệu và cơ quan giám sát. Nếu bạn có bất kỳ nhận xét hoặc câu hỏi nào liên quan đến Chính sách bảo mật của chúng tôi, nếu bạn có bất kỳ thắc mắc nào về quyền riêng tư của mình hoặc nếu bạn muốn khiếu nại về cách Dữ liệu cá nhân của bạn đang được Mixtiles xử lý, vui lòng liên hệ với DPO của chúng tôi tại dpo@Mixtilesvietnam.com .</span></p>
                        <p>&nbsp;</p>
                        <p><span style={{fontWeight: 400}}>Đại diện của Liên minh Châu Âu: Mixtiles B.V đã được chỉ định làm đại diện của Mixtiles tại Liên minh Châu Âu về các vấn đề bảo vệ dữ liệu theo Điều 27 của GDPR. Chỉ có thể liên hệ với Mixtiles B.V về những vấn đề liên quan đến việc xử lý Dữ liệu Cá nhân. Để thực hiện một yêu cầu như vậy, vui lòng gửi email đến hi@Mixtilesvietnam.com, hoặc liên hệ với Mixtiles B.V. qua đường bưu điện tại Stranwinskylaan 613, 1077 XX Amsterdam, Hà Lan. Nếu bạn là một cá nhân được bảo vệ bởi GDPR, bạn cũng có quyền khiếu nại với cơ quan giám sát của Liên minh Châu Âu.</span></p>
                        <p>&nbsp;</p>
                        <p><span style={{fontWeight: 400}}>Câu hỏi, Mối quan tâm hoặc Khiếu nại: Nếu bạn có bất kỳ nhận xét hoặc câu hỏi nào về Chính sách Bảo mật này hoặc nếu bạn có bất kỳ thắc mắc nào liên quan đến quyền riêng tư của mình, vui lòng liên hệ với chúng tôi tại </span><a href="mailto:hi@Mixtilesvietnam.com"><span style={{fontWeight: 400}}>hi@Mixtilesvietnam.com</span></a></p>
            </div></div></div>
        </StaticPage>
    </div>
}
export default PrivacyPolicy
