import React from 'react';
import StaticPage from '../containers/StaticPage'
import "../../src/assets/css/pages/StaticPages/TermOfUse.scss";

const TermOfUse = () => {
    return <div>
        <StaticPage>
            <div className="LegalDocumentPage">
                <div className="document-content">
                    <div>
                        <meta httpEquiv="Content-Type" content="text/html; charset=utf-8"/>
                        <title>terms-of-service-en</title>
                        <style type="text/css"
                               dangerouslySetInnerHTML={{__html: "\n        * {\n            font-family: Arial, sans-serif;\n            font-size: 11pt;\n        }\n\n        p:first-child {\n            font-size: large;\n            text-align: center;\n        }\n\n        a {\n            color: #F07;;\n        }\n    "}}/>

                        <p><strong>ĐIỀU KHOẢN SỬ DỤNG</strong></p>
                        <p>&nbsp;</p>
                        <p><strong>Điều khoản dịch vụ của Mixtiles</strong></p>
                        <p>&nbsp;</p>
                        <p><span style={{fontWeight: 400}}>Dưới đây là tổng quan về các điều khoản của chúng tôi. Chúng tôi thực sự khuyên bạn nên đọc thông tin pháp lý đầy đủ của chúng tôi bên dưới, vì đó là thông tin thực sự quan trọng. (Thêm vào đó, ai mà không thích đọc đi đọc lại một Điều khoản dịch vụ dài và hay?)</span></p>
                        <p>&nbsp;</p>
                        <p><span style={{fontWeight: 400}}>Bạn vẫn sở hữu tất cả các hình ảnh bạn đặt hàng từ chúng tôi. Bạn giữ bản quyền cho tất cả các hình ảnh của bạn. Chúng tôi sẽ không bán, chia sẻ hoặc sử dụng chúng cho bất kỳ mục đích nào khác ngoài việc in và giao hàng cho bạn.</span></p>
                        <p><span style={{fontWeight: 400}}>Chúng tôi cần quyền truy cập vào thư viện ảnh của bạn để hiển thị ảnh của bạn trong ứng dụng Mixtiles. Khi bạn mở ứng dụng của chúng tôi lần đầu tiên, ứng dụng sẽ yêu cầu bạn cấp quyền truy cập vào ảnh của bạn. Chúng tôi cần điều đó để có thể cho phép bạn chọn, cắt và sắp xếp các bức ảnh của bạn trong ứng dụng của chúng tôi. Nếu muốn, bạn có thể tắt quyền đó trong cài đặt của mình sau hoặc xóa ứng dụng để xóa quyền.</span></p>
                        <p><span style={{fontWeight: 400}}>Nếu bạn muốn, chúng tôi sẽ xóa tất cả ảnh và dữ liệu cá nhân của bạn khỏi hệ thống của chúng tôi. Tất cả những gì bạn cần làm là gửi cho chúng tôi email đến hi@Mixtilesvietnam.com từ địa chỉ email bạn đã nhập khi đặt hàng.</span></p>
                        <p><span style={{fontWeight: 400}}>Bạn đồng ý không đặt hàng bất kỳ hình ảnh nào bạn không sở hữu hoặc bất kỳ nội dung khiêu dâm hoặc phân biệt đối xử nào. Có rất nhiều người tham gia vào quá trình in, vì vậy chúng tôi không thể in bất kỳ hình ảnh nào có nội dung khỏa thân hoặc phản cảm. Chúng tôi cũng không thể in ảnh mà bạn không có quyền sử dụng. Nếu bạn gửi cho chúng tôi một bức tranh không phải của bạn và chúng tôi bị chủ sở hữu hợp pháp khởi kiện, bạn sẽ phải chịu mọi chi phí liên quan.</span></p>
                        <p><span style={{fontWeight: 400}}>Nếu có vấn đề với ô xếp của bạn hoặc nếu có bất kỳ vấn đề nào khác, chỉ cần gửi cho chúng tôi email tohi@Mixtilesvietnam.com hoặc trò chuyện thông qua ứng dụng. Chúng tôi sẽ cố gắng hết sức để giải quyết tất cả.</span></p>
                        <p><span style={{fontWeight: 400}}>Điều khoản dịch vụ thực tế</span></p>
                        <p>&nbsp;</p>
                        <p><span style={{fontWeight: 400}}>Mixtiles (như được định nghĩa bên dưới) cho phép người dùng tải lên hình ảnh và / hoặc hình ảnh ("Hình ảnh") lên trang web của chúng tôi ("Trang web") hoặc ứng dụng di động của chúng tôi (cùng với Trang web, "Ứng dụng") để in những Hình ảnh đó trên một gạch ốp tường ("Tile (s)").</span></p>
                        <p><span style={{fontWeight: 400}}>Vui lòng đọc kỹ các Điều khoản này. Bằng cách nhấp vào nút được đánh dấu "Tôi đồng ý", bạn đồng ý với các Điều khoản này. Các thay đổi có thể được thực hiện đối với các Điều khoản này theo thời gian. Nếu bạn không đồng ý với bất kỳ Điều khoản nào trong số này, vui lòng không nhấp vào nút được đánh dấu "Tôi đồng ý" và không sử dụng Ứng dụng hoặc Dịch vụ.</span></p>
                        <p>&nbsp;</p>
                        <p><strong>Sử dụng các dịch vụ</strong></p>
                        <p><span style={{fontWeight: 400}}>Việc sử dụng Dịch vụ và quyền truy cập vào Ứng dụng bị vô hiệu nếu bị cấm. Bằng cách sử dụng Dịch vụ, bạn tuyên bố và đảm bảo rằng (a) tất cả thông tin bạn gửi là trung thực và chính xác; (b) bạn từ 18 tuổi trở lên hoặc được sự cho phép của cha mẹ hoặc người giám hộ của bạn để tham gia vào các Điều khoản này và (c) có khả năng hình thành một hợp đồng ràng buộc; (d) việc bạn sử dụng Ứng dụng hoặc Dịch vụ không vi phạm bất kỳ luật hoặc quy định hiện hành nào hoặc bất kỳ nghĩa vụ nào mà bạn có thể có đối với bên thứ ba; (e) việc sử dụng Ứng dụng và Dịch vụ của bạn phải tuân thủ tất cả các luật và quy định hiện hành; (f) bạn hoàn toàn chịu trách nhiệm về việc có được sự đồng ý của cha mẹ hoặc người giám hộ ("Sự đồng ý của cha mẹ") trước khi chuyển cho chúng tôi bất kỳ thông tin nào, bao gồm cả hình ảnh, của bất kỳ trẻ em nào.</span></p>
                        <p>&nbsp;</p>
                        <p><span style={{fontWeight: 400}}>Bạn có thể sử dụng Ứng dụng và Dịch vụ theo và tuân theo các Điều khoản này. Mixtiles có thể thay đổi, cập nhật hoặc ngừng một số phần nhất định của Ứng dụng hoặc Dịch vụ. Những thay đổi này sẽ không áp dụng cho bất kỳ đơn đặt hàng chưa thanh toán nào và chúng tôi sẽ cố gắng thông báo cho bạn về bất kỳ thay đổi cơ bản nào, kể cả bằng cách thông báo trong Ứng dụng.</span></p>
                        <p>&nbsp;</p>
                        <p><span style={{fontWeight: 400}}>Để sử dụng Ứng dụng, bạn sẽ được yêu cầu cung cấp một số thông tin nhất định theo yêu cầu của Mixtiles.</span></p>
                        <p>&nbsp;</p>
                        <p><span style={{fontWeight: 400}}>Bạn có thể có tùy chọn liên kết Ứng dụng với một số dịch vụ của bên thứ ba, đôi khi có thể được liệt kê trong Ứng dụng, chẳng hạn như tài khoản Facebook, Google Photos hoặc Instagram của bạn ("Tài khoản được liên kết"). Bằng cách làm như vậy, bạn tuyên bố và đảm bảo rằng bạn có quyền cung cấp cho Mixtiles quyền truy cập vào thông tin tài khoản liên quan đến Tài khoản được liên kết đó và cung cấp cho Mixtiles quyền truy cập vào ảnh hoặc hình ảnh được lưu trong Tài khoản được liên kết đó.</span></p>
                        <p>&nbsp;</p>
                        <p><span style={{fontWeight: 400}}>Bạn hoàn toàn chịu trách nhiệm về bảo mật của hệ thống máy tính và / hoặc điện thoại di động và / hoặc thiết bị khác và tất cả hoạt động của bạn trên Ứng dụng. Chúng tôi không cảnh sát và không thể đảm bảo rằng chúng tôi sẽ tìm hiểu hoặc ngăn chặn mọi hành vi sử dụng Ứng dụng không phù hợp.</span></p>
                        <p>&nbsp;</p>
                        <p><span style={{fontWeight: 400}}>Theo luật hiện hành, Mixtiles có thể, vì bất kỳ lý do gì, theo quyết định riêng của mình và không cần thông báo, ngừng hoặc từ chối cung cấp Ứng dụng hoặc Dịch vụ cho bạn. Căn cứ cho việc từ chối đó có thể bao gồm nhưng không giới hạn ở (i) vi phạm văn bản hoặc tinh thần của các Điều khoản này, (ii) hành vi gian lận, quấy rối hoặc lạm dụng, (iii) hành vi bất hợp pháp hoặc có hại cho người dùng khác, bên thứ ba, hoặc lợi ích kinh doanh của Mixtiles, vi phạm các tuyên bố và bảo đảm của bạn ở đây hoặc vi phạm bất kỳ điều khoản nào của các Điều khoản này, hoặc (v) việc sử dụng quyền bồi hoàn của bạn với công ty phát hành thẻ tín dụng của bạn hoặc từ chối hoặc tranh chấp bất kỳ sự chấp thuận trước nào mà Mixtiles có được từ công ty thẻ tín dụng của bạn.</span></p>
                        <p>&nbsp;</p>
                        <p><span style={{fontWeight: 400}}>Nếu chúng tôi tin rằng, theo quyết định riêng của mình, đã xảy ra vi phạm các Điều khoản này hoặc bất kỳ hành vi bất hợp pháp hoặc không phù hợp nào, chúng tôi có thể thực hiện bất kỳ hành động sửa chữa nào khác mà chúng tôi cho là phù hợp. Chúng tôi có quyền điều tra các hành vi nghi ngờ vi phạm các Điều khoản này hoặc hành vi bất hợp pháp và không phù hợp trên Ứng dụng. Chúng tôi sẽ hoàn toàn hợp tác với bất kỳ cuộc điều tra thực thi pháp luật hoặc lệnh tòa yêu cầu hoặc chỉ đạo chúng tôi tiết lộ danh tính, hành vi hoặc (Người dùng) Nội dung (như được định nghĩa bên dưới) của bất kỳ ai được cho là đã vi phạm các Điều khoản này hoặc có hành vi bất hợp pháp liên quan đến Ứng dụng và / hoặc Dịch vụ.</span></p>
                        <p>&nbsp;</p>
                        <p><span style={{fontWeight: 400}}>Bất kỳ việc tạm dừng, chấm dứt hoặc hủy bỏ Dịch vụ sẽ không ảnh hưởng đến nghĩa vụ của bạn đối với Mixtiles theo các Điều khoản này (bao gồm nhưng không giới hạn ở quyền sở hữu, bồi thường, giới hạn trách nhiệm và nghĩa vụ thanh toán), cũng như sẽ không ảnh hưởng đến bất kỳ điều khoản nào khác ở đây, theo ý nghĩa của chúng và ngữ cảnh được thiết kế để tồn tại việc tạm ngừng, chấm dứt hoặc hủy bỏ như vậy.</span></p>
                        <p>&nbsp;</p>
                        <p><strong>Nội dung và Nội dung Người dùng</strong></p>
                        <p><span style={{fontWeight: 400}}>Một số loại nội dung nhất định có thể được cung cấp thông qua Ứng dụng hoặc Dịch vụ. "Nội dung" được sử dụng trong các Điều khoản này, gọi chung là tất cả nội dung trên hoặc được cung cấp trên Ứng dụng hoặc thông qua Dịch vụ, bao gồm mọi hình ảnh, ảnh chụp, tranh ảnh và bất kỳ sửa đổi hoặc dẫn xuất nào của những điều đã nói ở trên.</span></p>
                        <p>&nbsp;</p>
                        <p><span style={{fontWeight: 400}}>Ứng dụng có thể cho phép bạn tải lên một số nội dung nhất định bao gồm nhưng không giới hạn ở Hình ảnh và ảnh chụp. Tất cả nội dung do bạn tải lên được gọi là "Nội dung Người dùng". Nội dung Người dùng có thể bao gồm Dữ liệu nhạy cảm. Bạn đang và sẽ luôn chịu trách nhiệm hoàn toàn và tự chịu trách nhiệm về bất kỳ Nội dung Người dùng nào mà bạn tải lên Ứng dụng. CHÚNG TÔI TUYÊN BỐ VÀ BẢO ĐẢM RẰNG BẤT KỲ NỘI DUNG NÀO CỦA NGƯỜI DÙNG PHÙ HỢP VỚI TẤT CẢ LUẬT ÁP DỤNG, MÀ BẠN CÓ TẤT CẢ CÁC QUYỀN VÀ QUYỀN CẦN THIẾT ĐỂ NỘP BẤT KỲ NỘI DUNG NÀO CỦA NGƯỜI DÙNG THÔNG QUA ỨNG DỤNG VÀ DỊCH VỤ VÀ KHÔNG CÓ NỘI DUNG NÀO CỦA NGƯỜI DÙNG XÂM PHẠM HOẶC VI PHẠM QUYỀN SỞ HỮU BẤT KỲ BÊN THỨ BA , QUYỀN RIÊNG TƯ HOẶC CÔNG CỘNG HOẶC QUYỀN SỨC MẠNH. BẠN ĐẠI DIỆN VÀ BẢO ĐẢM RẰNG BẠN ĐÃ ĐẠT TẤT CẢ CÁC QUYỀN ĐƯỢC YÊU CẦU THEO LUẬT ÁP DỤNG, ĐỂ CUNG CẤP CÁC MIỀN CÓ DỮ LIỆU NHẠY CẢM CHO MỤC ĐÍCH XỬ LÝ CÁC DỮ LIỆU NHẠY CẢM THEO CÁC ĐIỀU KHOẢN NÀY VÀ THÔNG BÁO RIÊNG TƯ CỦA CHÚNG TÔI VÀ CÁC BẠN CÓ PHÙ HỢP LUẬT ÁP DỤNG, TỪ BẤT KỲ ĐỐI TƯỢNG DỮ LIỆU HOẶC PHỤ HUYNH HOẶC NGƯỜI BẢO LÃNH NÀO CỦA ĐỐI TƯỢNG DỮ LIỆU, NHƯ ĐƯỢC ÁP DỤNG, TRONG ĐÓ DỮ LIỆU, BAO GỒM DỮ LIỆU NHẠY CẢM, ĐƯỢC NỘP THÔNG QUA ỨNG DỤNG VÀ DỊCH VỤ. Mixtile không có nghĩa vụ chấp nhận bất kỳ yêu cầu nào để in hoặc duy trì bất kỳ Nội dung Người dùng nào. Hơn nữa, Mixtiles có quyền xóa và xóa vĩnh viễn bất kỳ Nội dung Người dùng nào do bạn tải lên mà không cần thông báo và vì bất kỳ lý do gì. CHÚNG TÔI KHÔNG KẾT THÚC BẤT KỲ NỘI DUNG NÀO (BAO GỒM KHÔNG GIỚI HẠN BẤT KỲ NỘI DUNG NÀO CỦA NGƯỜI DÙNG) HOẶC BẤT KỲ Ý KIẾN, KHUYẾN NGHỊ HOẶC LỜI KHUYÊN NÀO ĐƯỢC THỂ HIỆN TRONG BẤT KỲ NỘI DUNG NÀO, VÀ CHÚNG TÔI TUYÊN BỐ TỪ CHỐI BẤT KỲ VÀ TẤT CẢ TRÁCH NHIỆM PHÁP LÝ LIÊN QUAN ĐẾN NỘI DUNG.</span></p>
                        <p>&nbsp;</p>
                        <p><span style={{fontWeight: 400}}>CHÚNG TÔI TỪ CHỐI TẤT CẢ TRÁCH NHIỆM PHÁP LÝ, LIÊN QUAN ĐẾN HÌNH THỨC HÀNH ĐỘNG ĐỐI VỚI CÁC HÀNH VI HOẶC LÝ DO CỦA NGƯỜI DÙNG (BAO GỒM NHỮNG NGƯỜI DÙNG KHÔNG ĐƯỢC KHAI THÁC) KHÔNG PHẢI DO SỰ GIẢM ĐAU CỦA MIXTILES HOẶC NGUYÊN NHÂN SỢ HÃI, BAO GỒM NHỮNG HÀNH VI HAY DO VIỆC SỬ DỤNG KHÁC HAY DỊCH VỤ CỦA CHÚNG TÔI .</span></p>
                        <p>&nbsp;</p>
                        <p><span style={{fontWeight: 400}}>Mixtiles có thể giữ lại Nội dung Người dùng, bao gồm cả Hình ảnh (bao gồm trong tài khoản của bạn dưới dạng lịch sử đặt hàng của bạn) miễn là tài khoản của bạn hợp lệ và không bị bạn hoặc chúng tôi chấm dứt, vì bất kỳ lý do gì. Bạn có thể yêu cầu chúng tôi xóa bất kỳ Nội dung Người dùng nào, bao gồm cả Hình ảnh, bằng cách gửi email cho chúng tôi, nêu rõ yêu cầu của bạn, như được nêu chi tiết trong Thông báo về Quyền riêng tư của chúng tôi. Bất kỳ Hình ảnh nào do bạn tải lên Dịch vụ và không do bạn chọn để in trên các Ô sẽ tự động bị xóa sau ba mươi (30) ngày kể từ ngày bạn tải (các) Hình ảnh lên.</span></p>
                        <p>&nbsp;</p>
                        <p><strong>Giới hạn Nội dung Người dùng</strong></p>
                        <p><span style={{fontWeight: 400}}>Không giới hạn những điều đã nói ở trên, bạn đồng ý rằng bạn sẽ không truyền tải, gửi hoặc tải lên bất kỳ Nội dung Người dùng nào hoặc hành động theo bất kỳ cách nào: (a) hạn chế hoặc ngăn cản việc sử dụng Ứng dụng và / hoặc Dịch vụ; (b) vi phạm các quyền hợp pháp của người khác; (c) vi phạm (hoặc dẫn đến vi phạm) sở hữu trí tuệ, đạo đức, công khai, quyền riêng tư hoặc các quyền khác của bất kỳ bên thứ ba nào; (d) là (hoặc bạn tin tưởng một cách hợp lý hoặc nên tin một cách hợp lý là) bị đánh cắp, bất hợp pháp, hàng giả, gian lận, vi phạm bản quyền, trái phép hoặc bạo lực, hoặc đang tiến hành bất kỳ hoạt động bất hợp pháp, hàng giả, gian lận, vi phạm bản quyền, trái phép hoặc bạo lực nào, hoặc liên quan đến (hoặc bạn tin tưởng một cách hợp lý hoặc nên tin một cách hợp lý là có liên quan đến) bất kỳ tài liệu nào bị đánh cắp, bất hợp pháp, giả mạo, gian lận, vi phạm bản quyền hoặc trái phép; (e) không tuân thủ tất cả các luật, quy tắc và quy định hiện hành; (f) áp đặt một tải trọng lớn một cách bất hợp lý hoặc không tương xứng đối với cơ sở hạ tầng của chúng tôi; hoặc (g) các bài đăng, lưu trữ, truyền tải, cung cấp hoặc gạ gẫm bất cứ thứ gì có chứa những điều sau đây hoặc mà bạn biết có chứa các liên kết đến những điều sau đây hoặc đến các vị trí có chứa các liên kết đến những điều sau: tài liệu mà chúng tôi xác định là gây khó chịu (bao gồm tài liệu cổ xúy hoặc ca Tranh lòng căm thù, bạo lực, cố chấp hoặc bất kỳ thực thể nào trong quá khứ hoặc hiện tại chủ yếu dành cho các mục đích hoặc các mục liên quan đến một thực thể đó), (2) tài liệu không nhạy cảm về chủng tộc hoặc sắc tộc, hoặc phỉ báng, quấy rối hoặc đe dọa, (3) nội dung khiêu dâm hoặc tài liệu tục tĩu và bất kỳ thứ gì mô tả trẻ em trong các tình huống khiêu gợi, cho dù có hoặc không mô tả trẻ em thực tế hoặc có thể gây hại cho trẻ vị thành niên, (4) bất kỳ vi-rút, sâu, ngựa thành Troy hoặc thành phần có hại hoặc gây rối khác, hoặc ( 5) bất kỳ điều gì khuyến khích hành vi sẽ bị coi là tội hình sự, làm phát sinh trách nhiệm dân sự, vi phạm bất kỳ luật hoặc quy định nào hoặc không phù hợp hoặc gây khó chịu.</span></p>
                        <p>&nbsp;</p>
                        <p><strong>Hạn chế sử dụng</strong></p>
                        <p><span style={{fontWeight: 400}}>Bạn không được làm hoặc cố gắng thực hiện hoặc tạo điều kiện cho bên thứ ba thực hiện bất kỳ việc nào sau đây: (1) cố gắng giải mã, dịch ngược, tháo rời hoặc thiết kế ngược bất kỳ phần mềm nào được sử dụng để cung cấp Dịch vụ hoặc Ứng dụng mà không có sự hỗ trợ trước của chúng tôi ủy quyền bằng văn bản, bao gồm việc đóng khung hoặc sao chép bất kỳ phần nào của Ứng dụng hoặc cố gắng thiết kế ngược lại bất kỳ công nghệ nào được sử dụng trong các Ô; (2) phá vỡ, vô hiệu hóa hoặc can thiệp vào các tính năng liên quan đến bảo mật của Dịch vụ hoặc Ứng dụng hoặc các tính năng ngăn chặn hoặc hạn chế việc sử dụng hoặc sao chép bất kỳ nội dung nào; (3) sử dụng Ứng dụng, Nội dung hoặc Dịch vụ liên quan đến bất kỳ nỗ lực thương mại nào theo bất kỳ cách nào, ngoại trừ các mục đích được nêu cụ thể trong các Điều khoản này; (4) sử dụng bất kỳ rô bốt, trình thu thập dữ liệu, ứng dụng tìm kiếm hoặc truy xuất trang web nào hoặc bất kỳ thiết bị hoặc quy trình thủ công hoặc tự động nào khác để truy xuất, lập chỉ mục, khai thác dữ liệu hoặc theo bất kỳ cách nào sao chép hoặc phá vỡ cấu trúc điều hướng hoặc bản trình bày của Ứng dụng; hoặc (5) sử dụng Ứng dụng, Nội dung hoặc Dịch vụ theo bất kỳ cách nào không được các Điều khoản này cho phép.</span></p>
                        <p>&nbsp;</p>
                        <p><strong>Sở hữu trí tuệ</strong></p>
                        <p><span style={{fontWeight: 400}}>Mixtile, các chi nhánh của nó hoặc người cấp phép của nó, tùy từng trường hợp, sở hữu Ứng dụng và Dịch vụ, bao gồm tất cả các quyền sở hữu trí tuệ trên toàn thế giới trong Ứng dụng và các nhãn hiệu, nhãn hiệu dịch vụ và biểu trưng có trong đó đã được đăng ký và chưa đăng ký. Trừ khi được cho phép rõ ràng ở đây, bạn không được sao chép, phát triển thêm, tái sản xuất, tái xuất bản, sửa đổi, thay đổi, tải xuống, đăng, phát sóng, truyền tải hoặc sử dụng Ứng dụng hoặc Dịch vụ. Bạn sẽ không xóa, thay đổi hoặc che giấu bất kỳ thông báo bản quyền, thương hiệu, nhãn hiệu dịch vụ hoặc các quyền sở hữu khác được tích hợp trong Ứng dụng hoặc Dịch vụ, nếu có. Tất cả các nhãn hiệu đều là nhãn hiệu hoặc nhãn hiệu đã đăng ký của chủ sở hữu tương ứng. Không có điều khoản nào trong các Điều khoản này cấp cho bạn bất kỳ quyền nào để sử dụng bất kỳ nhãn hiệu, nhãn hiệu dịch vụ, biểu tượng hoặc tên thương mại nào của Mixtiles hoặc bất kỳ bên thứ ba nào.</span></p>
                        <p>&nbsp;</p>
                        <p><span style={{fontWeight: 400}}>Bạn sở hữu những Hình ảnh mà bạn tải lên Ứng dụng và / hoặc Dịch vụ và tất cả các quyền sở hữu trí tuệ liên quan đến những Hình ảnh đó. Mixtile sẽ chỉ sử dụng Hình ảnh cho các mục đích cung cấp Dịch vụ. Với mục đích nhận các Dịch vụ và như một phần của (các) Tile, bạn đang cấp cho Mixtile quyền sử dụng Hình ảnh, theo các điều dưới đây:</span></p>
                        <p>&nbsp;</p>
                        <p><span style={{fontWeight: 400}}>Bằng cách gửi hoặc tải lên bất kỳ Nội dung và / hoặc Hình ảnh của Người dùng nào, bạn cấp cho Mixtiles và những người kế nhiệm của nó một giấy phép toàn cầu, có giới hạn, không độc quyền, miễn phí bản quyền, vĩnh viễn, có thể cấp phép lại và có thể chuyển nhượng để sử dụng, sao chép và in Nội dung Người dùng đó và / hoặc Hình ảnh trên (các) Tile.</span></p>
                        <p>&nbsp;</p>
                        <p><strong>Bản quyền</strong></p>
                        <p><span style={{fontWeight: 400}}>Chính sách của Mixtiles là không xâm phạm hoặc vi phạm quyền sở hữu trí tuệ hoặc các quyền khác của bất kỳ bên thứ ba nào và Mixtiles sẽ từ chối sử dụng và xóa bất kỳ Nội dung người dùng nào liên quan đến Ứng dụng vi phạm quyền của bất kỳ bên thứ ba nào. Theo Đạo luật Bản quyền Thiên niên kỷ Kỹ thuật số năm 1998 ("DMCA"), Mixtiles sẽ xóa bất kỳ Nội dung nào (bao gồm nhưng không giới hạn bất kỳ Nội dung Người dùng nào) nếu được thông báo thích hợp rằng tài liệu đó vi phạm quyền của bên thứ ba và có thể làm như vậy theo quyết định riêng của mình mà không thông báo trước cho người dùng bất cứ lúc nào. Chính sách của Mixtiles là chấm dứt tài khoản của những người tái vi phạm trong những trường hợp thích hợp.</span></p>
                        <p>&nbsp;</p>
                        <p><span style={{fontWeight: 400}}>Bạn đang ở vị trí tốt nhất để đánh giá liệu Nội dung Người dùng có vi phạm quyền sở hữu trí tuệ hoặc quyền cá nhân của bất kỳ bên thứ ba nào hay không. Bạn hoàn toàn chịu trách nhiệm về việc tránh vi phạm quyền sở hữu trí tuệ hoặc quyền cá nhân của người khác liên quan đến Nội dung Người dùng.</span></p>
                        <p>&nbsp;</p>
                        <p><span style={{fontWeight: 400}}>Nếu bạn cho rằng nội dung nào đó xuất hiện trên Ứng dụng vi phạm bản quyền của bạn, bạn có thể gửi cho chúng tôi thông báo yêu cầu xóa hoặc chặn quyền truy cập vào ứng dụng đó. Nếu bạn cho rằng một thông báo như vậy đã được gửi nhầm chống lại bạn, DMCA cho phép bạn gửi thông báo phản đối cho chúng tôi. Thông báo và thông báo phản đối phải đáp ứng các yêu cầu của DMCA. Chúng tôi khuyên bạn nên tham khảo ý kiến cố vấn pháp lý của mình trước khi gửi thông báo hoặc thông báo phản đối. Xin lưu ý rằng có thể bị phạt đáng kể đối với các tuyên bố sai. Gửi thông báo và phản hồi cho chúng tôi bằng cách liên hệ với hi@Mixtilesvietnam.com.</span></p>
                        <p>&nbsp;</p>
                        <p><strong>Phí và Thanh toán</strong></p>
                        <p><span style={{fontWeight: 400}}>Liên quan đến việc bạn mua Tranh thông qua Dịch vụ, bạn sẽ được yêu cầu cung cấp thông tin thanh toán thông thường như tên, địa chỉ thanh toán và thông tin thẻ tín dụng cho Mixtiles hoặc (các) bộ xử lý thanh toán bên thứ ba của nó. Bạn đồng ý thanh toán Phí cho Mixtiles như được quy định trong Ứng dụng trong quá trình mua hàng cho bất kỳ giao dịch đã xác nhận nào được thực hiện liên quan đến tài khoản của bạn theo các Điều khoản này bằng một trong các phương thức được mô tả trên Ứng dụng. Theo đây, bạn cho phép thu các số tiền đó bằng cách tính phí vào thẻ tín dụng do Mixtile cung cấp, trực tiếp hoặc gián tiếp, thông qua bộ xử lý thanh toán trực tuyến của bên thứ ba hoặc bằng một trong các phương thức thanh toán được mô tả trên Ứng dụng. Nếu bạn được hướng dẫn đến (các) bộ xử lý thanh toán của bên thứ ba, bạn có thể phải tuân theo các điều khoản và điều kiện chi phối việc sử dụng dịch vụ của bên thứ ba đó và các hoạt động thu thập Dữ liệu Cá nhân của bên thứ ba đó. Vui lòng xem lại các điều khoản và điều kiện và chính sách bảo mật trước khi sử dụng Dịch vụ.</span></p>
                        <p>&nbsp;</p>
                        <p><span style={{fontWeight: 400}}>Trừ khi được cung cấp rõ ràng bên dưới, phí không được hoàn lại.</span></p>
                        <p>&nbsp;</p>
                        <p><strong>Tiền hoàn lại</strong></p>
                        <p><span style={{fontWeight: 400}}>Chúng tôi muốn bạn hài lòng với (các) Tranh của bạn. Nếu chúng tôi đã sai sót trong việc chuẩn bị Gạch của bạn hoặc nếu chúng đến bị hỏng, chúng tôi sẽ rất sẵn lòng hoàn lại tiền. Tất nhiên, bạn đã nhầm lẫn trong việc đặt hàng hoặc chỉ đổi ý, thì theo luật hiện hành, đơn đặt hàng của bạn sẽ không đủ điều kiện để được hoàn lại tiền.</span></p>
                        <p>&nbsp;</p>
                        <p><span style={{fontWeight: 400}}>Nếu bạn muốn yêu cầu hoàn lại tiền, vui lòng liên hệ với chúng tôi thông qua tính năng trò chuyện của Ứng dụng, bằng cách gửi email cho chúng tôi theo địa chỉ hi@Mixtilesvietnam.com hoặc bằng cách gửi yêu cầu bằng văn bản đến địa chỉ của chúng tôi tại Ahad Ha'Am 54, Tel Aviv -Yafo, Israel 6520216. Nếu lý do bạn muốn được hoàn lại tiền là do Gạch bạn nhận được không được in đúng cách hoặc có một số hư hỏng khác, sẽ rất hữu ích nếu bạn gửi kèm hình ảnh của Gạch cùng với yêu cầu của mình.</span></p>
                        <p>&nbsp;</p>
                        <p><strong>Ứng dụng và dịch vụ của bên thứ ba</strong></p>
                        <p><span style={{fontWeight: 400}}>Các phần của Ứng dụng và / hoặc Dịch vụ có thể liên quan đến việc liên kết đến hoặc sử dụng các trang web của các bên thứ ba. Ứng dụng cũng có thể cung cấp cho bạn các liên kết để truy cập các trang web của các nhà cung cấp bên thứ ba, bao gồm nhưng không giới hạn, cho mục đích xem xét hoặc sử dụng dịch vụ của họ. Chúng tôi không kiểm soát các trang web và / hoặc ứng dụng di động của bên thứ ba và tất cả việc sử dụng các trang web và / hoặc ứng dụng và dịch vụ di động của bên thứ ba đều do bạn tự chịu rủi ro. Ngoài ra, Mixtiles không thể chịu trách nhiệm đối với bất kỳ khoản thanh toán nào được xử lý hoặc gửi thông qua các trang web và / hoặc ứng dụng di động của bên thứ ba đó hoặc đối với các chính sách bảo mật của bất kỳ trang web nào như vậy. Mixtile không chịu trách nhiệm về nội dung hoặc dịch vụ có sẵn trên các trang web và / hoặc ứng dụng di động đó. Mixtile không xác nhận bất kỳ sản phẩm hoặc dịch vụ nào do bên thứ ba cung cấp và chúng tôi kêu gọi người dùng của mình thận trọng khi sử dụng các trang web của bên thứ ba.</span></p>
                        <p>&nbsp;</p>
                        <p><strong>Tuyên bố từ chối trách nhiệm và Tuyên bố từ chối bảo hành</strong></p>
                        <p><span style={{fontWeight: 400}}>Việc bạn sử dụng Ứng dụng, Dịch vụ và (các) Ô là do bạn quyết định và tự chịu rủi ro. Ứng dụng, nội dung trong đó (bao gồm cả Nội dung của Người dùng), Dịch vụ và Ô xếp được cung cấp trên cơ sở "NGUYÊN TRẠNG" và "CÓ SN" mà không có bất kỳ bảo đảm nào dưới bất kỳ hình thức nào. Mặc dù chúng tôi nỗ lực hợp lý để in Hình ảnh trên (các) Tranh giống với Hình ảnh do bạn cung cấp thông qua Ứng dụng nhất có thể, chúng tôi không đưa ra bất kỳ bảo đảm hoặc tuyên bố nào về điều đó. Chúng tôi không đại diện hoặc đảm bảo rằng (các) Tranh sẽ hữu ích cho nhu cầu của bạn.</span></p>
                        <p>&nbsp;</p>
                        <p><span style={{fontWeight: 400}}>ĐỐI VỚI MỞ RỘNG ĐẦY ĐỦ NHẤT ĐƯỢC PHÁP LUẬT ÁP DỤNG CHO PHÉP, CHÚNG TÔI TUYÊN BỐ TUYÊN BỐ TỪ CHỐI TẤT CẢ CÁC BẢO ĐẢM CỦA BẤT KỲ HÌNH THỨC NÀO, RÕ RÀNG, NGỤ Ý HOẶC TRUYỆN, LIÊN QUAN ĐẾN: (A) ỨNG DỤNG, NỘI DUNG (BAO GỒM NỘI DUNG CỦA NGƯỜI DÙNG), DỊCH VỤ VÀ GẠCH, BAO GỒM KHÔNG GIỚI HẠN CÁC BẢO ĐẢM VỀ TIÊU ĐỀ, KHẢ NĂNG LAO ĐỘNG, PHÙ HỢP VỚI MỤC ĐÍCH CỤ THỂ, KHÔNG VI PHẠM QUYỀN SỞ HỮU, KHÓA HỌC THỰC HIỆN HOẶC KHÓA HỌC KINH DOANH. ĐỐI VỚI MỞ RỘNG ĐẦY ĐỦ NHẤT ĐƯỢC PHÁP LUẬT ÁP DỤNG CHO PHÉP, CHÚNG TÔI TỪ CHỐI BẤT KỲ BẢO ĐẢM NÀO, RÕ RÀNG HOẶC NGỤ Ý, (I) LIÊN QUAN ĐẾN TÍNH BẢO MẬT, CHÍNH XÁC, TIN CẬY, THỜI HẠN VÀ HIỆU SUẤT CỦA ỨNG DỤNG VÀ DỊCH VỤ; HOẶC (II) RẰNG ỨNG DỤNG VÀ DỊCH VỤ SẼ KHÔNG CÓ LỖI HOẶC BẤT KỲ LỖI NÀO SẼ ĐƯỢC SỬA CHỮA; HOẶC (III) LIÊN QUAN ĐẾN HIỆU SUẤT HOẶC CHÍNH XÁC, CHẤT LƯỢNG, TIỀN TỆ, HOÀN TOÀN HOẶC HỮU ÍCH CỦA BẤT KỲ THÔNG TIN NÀO DO ỨNG DỤNG VÀ DỊCH VỤ CUNG CẤP; (B) ĐÍNH KÈM, DÁN VÀ / HOẶC DÁN LẠI GẠCH. VIỆC LOẠI TRỪ BẢO ĐẢM BẮT ĐẦU SẼ KHÔNG MỞ RỘNG ĐỐI VỚI BẤT KỲ SỰ ĐÀM PHÁN HOẶC NGUYÊN NHÂN SÂU SẮC NÀO CỦA CÁC LOẠI Mixtiles.</span></p>
                        <p>&nbsp;</p>
                        <p><span style={{fontWeight: 400}}>Chúng tôi không chịu trách nhiệm về chất lượng của (các) Tranh hoặc việc bạn hoặc bất kỳ bên thứ ba nào khác sử dụng chúng, cũng như không chịu trách nhiệm về việc vận chuyển (các) Tranh và / hoặc trạng thái mà Tranh ( s) sẽ đến địa chỉ do bạn cung cấp trong quá trình đăng ký và / hoặc bất kỳ thiệt hại nào có thể xảy ra nếu bạn chọn gắn, dán và / hoặc dán lại (các) Tranh trên bất kỳ bề mặt nào và / hoặc bất kỳ thứ gì khác (vật lý ) thiệt hại dưới bất kỳ hình thức nào do bạn hoặc bất kỳ ai khác trên hoặc từ bất kỳ bề mặt nào gây ra bởi các Gạch, phần đính kèm hoặc sự tách rời của Gạch. Không có lời khuyên hoặc thông tin nào, dù bằng miệng hay bằng văn bản, do bạn thu được từ chúng tôi, sẽ tạo ra bất kỳ bảo đảm nào không được nêu rõ trong các Điều khoản này. Nếu bạn chọn dựa vào những thông tin như vậy, bạn hoàn toàn tự chịu rủi ro. Một số tiểu bang hoặc khu vực pháp lý không cho phép loại trừ một số bảo hành nhất định. Theo đó, một số loại trừ trên có thể không áp dụng cho bạn. Kiểm tra luật pháp địa phương của bạn để biết bất kỳ hạn chế hoặc giới hạn nào liên quan đến việc loại trừ các bảo đảm ngụ ý.</span></p>
                        <p>&nbsp;</p>
                        <p><strong>Trách nhiệm hữu hạn</strong></p>
                        <p><span style={{fontWeight: 400}}>Chúng tôi không chịu trách nhiệm đối với bất kỳ lỗi, thiếu sót, gián đoạn, xóa, khiếm khuyết, chậm trễ trong vận hành hoặc truyền tải, lỗi đường truyền liên lạc, trộm cắp hoặc phá hủy hoặc truy cập trái phép vào, hoặc thay đổi bất kỳ Nội dung hoặc Dịch vụ nào, chất lượng, phần đính kèm hoặc tách rời của (Các) ô và chất lượng của Hình ảnh được in trên (các) ô. Chúng tôi không chịu trách nhiệm về bất kỳ sự cố hoặc trục trặc kỹ thuật nào của bất kỳ mạng điện thoại hoặc đường dây nào, hệ thống máy tính trực tuyến, máy chủ hoặc nhà cung cấp, thiết bị máy tính, phần mềm, lỗi của bất kỳ email nào do sự cố kỹ thuật hoặc tắc nghẽn giao thông trên Internet hoặc trên bất kỳ Ứng dụng nào hoặc Dịch vụ hoặc sự kết hợp của chúng, bao gồm bất kỳ thương tích hoặc thiệt hại nào cho bạn hoặc cho điện thoại di động hoặc máy tính của bất kỳ người nào liên quan đến hoặc kết quả từ việc tham gia hoặc tải xuống tài liệu và / hoặc tải lên (các) Hình ảnh liên quan đến Ứng dụng hoặc Dịch vụ. Trong mọi trường hợp, chúng tôi sẽ không chịu trách nhiệm về bất kỳ mất mát hoặc thiệt hại nào, bao gồm cả thương tích cá nhân hoặc tử vong do sử dụng Ứng dụng hoặc Dịch vụ, từ bất kỳ Nội dung nào được đăng trên hoặc thông qua Ứng dụng hoặc Dịch vụ hoặc từ hành vi của bất kỳ người dùng Ứng dụng nào hoặc Dịch vụ, cho dù trực tuyến hay ngoại tuyến.</span></p>
                        <p>&nbsp;</p>
                        <p><span style={{fontWeight: 400}}>TRONG MỌI SỰ KIỆN, CHÚNG TÔI HOẶC BẤT KỲ NHÂN VIÊN, GIÁM ĐỐC, NHÂN VIÊN, CÔNG TY CỔ PHẦN HOẶC ĐẠI LÝ NÀO CỦA CHÚNG TÔI CHỊU TRÁCH NHIỆM PHÁP LÝ VỚI BẠN VỀ BẤT KỲ THIỆT HẠI NÀO, BAO GỒM KHÔNG GIỚI HẠN ẤN TƯỢNG, SỰ CỐ, ĐẶC BIỆT, CÁ NHÂN HOẶC HẬU QUẢ GÂY RA CỦA BẠN VIỆC SỬ DỤNG ỨNG DỤNG, DỊCH VỤ VÀ / HOẶC (S), BAO GỒM NHƯNG KHÔNG GIỚI HẠN VỀ CHẤT LƯỢNG, ĐỘ CHÍNH XÁC HOẶC TIỆN ÍCH CỦA LỐP ĐƯỢC CUNG CẤP NHƯ MỘT PHẦN HOẶC THÔNG QUA ỨNG DỤNG HOẶC DỊCH VỤ, BAO GỒM CÁC THIỆT HẠI CÓ THỂ CẦN ĐƯỢC VÀ THÌ HAY KHÔNG CHÚNG TÔI ĐÃ ĐƯỢC TƯ VẤN VỀ KHẢ NĂNG CỦA CÁC THIỆT HẠI NHƯ VẬY. GIỚI HẠN TRÁCH NHIỆM PHÁP LÝ BẮT ĐẦU SẼ ÁP DỤNG ĐỐI VỚI PHẠM VI ĐẦY ĐỦ NHẤT ĐƯỢC PHÁP LUẬT CHO PHÉP TRONG ĐIỀU KHOẢN ÁP DỤNG VÀ TRONG TRƯỜNG HỢP KHÔNG CÓ TRÁCH NHIỆM PHÁP LÝ TỐI ĐA CỦA CHÚNG TÔI ĐỐI VỚI BẠN THEO BẤT KỲ (CÁC) NGUYÊN NHÂN NÀO CỦA HÀNH VI (DÙ BẠN TRONG HỢP ĐỒNG, SỐ TIỀN HOẶC NGOÀI) ĐÃ THANH TOÁN CHO CHÚNG TÔI TRONG VÒNG TRĂM THÁNG NGAY LẬP TỨC KHIẾU NẠI HOẶC BẢNG YÊU CẦU ÁP DỤNG. CÁC GIỚI HẠN TRÁCH NHIỆM PHÁP LÝ BẮT ĐẦU SẼ KHÔNG MỞ RỘNG ĐỐI VỚI BẤT KỲ KHẢ NĂNG GIẢM CÂN NÀO HOẶC BẤT CỨ NGUYÊN NHÂN SẼ HOẶC HOÀN TOÀN NÀO CỦA Mixtiles.</span></p>
                        <p>&nbsp;</p>
                        <p><strong>Sự bồi thường</strong></p>
                        <p><span style={{fontWeight: 400}}>Bạn đồng ý bồi thường, bảo vệ và giữ các Mixtile vô hại và từng nhân viên, giám đốc, cán bộ, nhà thầu phụ và đại lý của công ty chống lại bất kỳ và tất cả các khiếu nại, thiệt hại hoặc chi phí hoặc chi phí (bao gồm cả chi phí tòa án và phí luật sư) phát sinh trực tiếp hoặc gián tiếp từ việc: (a) việc bạn hoặc bất kỳ ai sử dụng máy tính, thiết bị di động hoặc mật khẩu của bạn vi phạm các Điều khoản này (cho dù được ủy quyền hay trái phép); (b) bất kỳ khiếu nại, mất mát hoặc thiệt hại nào do bạn sử dụng hoặc cố gắng sử dụng Ứng dụng hoặc Dịch vụ, bao gồm bất kỳ Hình ảnh nào được tải lên Ứng dụng hoặc Dịch vụ; (c) bạn vi phạm bất kỳ luật hoặc quy định nào hoặc bất kỳ nghĩa vụ, đại diện hoặc bảo đảm nào của bạn dưới đây; (d) việc bạn vi phạm bất kỳ quyền nào của bất kỳ bên thứ ba nào; và (e) bất kỳ vấn đề nào khác mà bạn chịu trách nhiệm dưới đây hoặc theo luật hiện hành.</span></p>
                        <p><br /><br /><br /></p>
                        <p><strong>Tuyên bố về khả năng tiếp cận</strong></p>
                        <p>&nbsp;</p>
                        <p><span style={{fontWeight: 400}}>Chúng tôi cam kết đảm bảo rằng người khuyết tật có quyền truy cập vào hàng hóa và dịch vụ của chúng tôi, bao gồm cả những hàng hóa và dịch vụ được cung cấp thông qua trang web của chúng tôi, www.mixtilesvietnam.com và ứng dụng di động. Do đó, chúng tôi cố gắng tuân thủ Nguyên tắc hỗ trợ tiếp cận nội dung web (“WCAG”) 2.0 Mức A và AA, một bộ nguyên tắc được phát triển bởi World Wide Web Consortium và được sử dụng để đảm bảo rằng mọi người đều có thể truy cập nội dung kỹ thuật số. Chúng tôi cũng làm việc với các nhóm vận động, các chuyên gia tư vấn về khả năng tiếp cận và khả năng sử dụng, và những người khuyết tật để đảm bảo rằng trang web và các ứng dụng di động của chúng tôi hoạt động bình thường. Chúng tôi luôn học hỏi và tìm cách cải thiện khả năng tiếp cận tới các bạn.</span></p>
                        <p><span style={{fontWeight: 400}}>Dưới đây là một số bước chúng tôi đã thực hiện để cải thiện quyền truy cập vào trang web và các ứng dụng di động của chúng tôi:</span></p>
                        <p>&nbsp;</p>
                        <p><span style={{fontWeight: 400}}>Tương đương Văn bản: Chúng tôi cung cấp chi tiết văn bản thay thế cho các hình ảnh thích hợp và các yếu tố không phải văn bản khác.</span></p>
                        <p>&nbsp;</p>
                        <p><span style={{fontWeight: 400}}>Truy cập toàn bộ bằng bàn phím: Trang web của chúng tôi được xây dựng để có thể truy cập bằng bàn phím.</span></p>
                        <p>&nbsp;</p>
                        <p><span style={{fontWeight: 400}}>Tính nhất quán của trang web: Chúng tôi nhất quán trong cách chúng tôi xây dựng trang web và các ứng dụng di động để chúng hoạt động giống nhau mỗi khi bạn tương tác với chúng.</span></p>
                        <p>&nbsp;</p>
                        <p><span style={{fontWeight: 400}}>Cấu trúc trang web: Chúng tôi sử dụng các tiêu đề, danh sách, đoạn văn, biểu định kiểu thích hợp và các tính năng định dạng khác để khách có thể dễ dàng sử dụng trang web với công nghệ hỗ trợ.</span></p>
                        <p>&nbsp;</p>
                        <p><span style={{fontWeight: 400}}>Liên kết: Nhiều liên kết có thuộc tính tiêu đề mô tả liên kết chi tiết hơn, trừ khi văn bản của liên kết đã mô tả đầy đủ mục tiêu.</span></p>
                    </div>
                </div>
            </div>
        </StaticPage>
    </div>
}
export default TermOfUse
